name: Update Submodule

on:
  workflow_dispatch:

jobs:
  sync-submodule:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/submodule-sync-action@v1
        with:
          path: iginx
          ref: main
          pr_branch: automated-submodule-update
          target_branch: main
