name: Upload Binaries to Github Release

on:
  release:
    types:
      - published
      - created

jobs:
  build:
    uses: ./.github/workflows/build.yml
  upload-package:
    name: Upload Package to Github Release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - uses: actions/download-artifact@v4
      - uses: svenstaro/upload-release-action@v2
        with:
          file: "*.jar"
          file_glob: true
      - uses: actions/checkout@v4
      - uses: svenstaro/upload-release-action@v2
        with:
          file: README.md
          asset_name: tutorial.md